export const WS_EVENTS = {
  ORDER_SENT_TO_KDS: "ORDER_SENT_TO_KDS",
  KDS_STAGE_UPDATED: "KDS_STAGE_UPDATED",
  KDS_ITEM_COMPLETED: "KDS_ITEM_COMPLETED",
  TABLE_STATUS_CHANGED: "TABLE_STATUS_CHANGED",
  SESSION_CLOSED: "SESSION_CLOSED",
  ORDER_PAID: "ORDER_PAID",
};
